name: Deploy

# Ручной запуск с выбором ветки
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        default: 'main'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1. Клонируем код (для тестов перед деплоем)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # 2. Сборка и тесты Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

      # 3. Деплой на сервер через SSH
      - name: Deploy server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{secrets.SERVER_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            BRANCH="${{ github.event.inputs.branch }}"
            cd /opt/app || { echo "Directory /opt/app not found"; exit 1; }
            
            # Получаем последнюю версию выбранной ветки
            git fetch origin $BRANCH
            git reset --hard origin/$BRANCH

            echo "Deploying branch: $BRANCH"
            echo "Last commits:"
            git log -3 --oneline

            docker compose down
            docker compose up -d --build